### ISSUE TITLE
Folder path location in config file

### ISSUE THREAD

**Issue by Sai-1411** [cmartinezal/Download-folder-Alfresco#1]
Hi **@cmartinezal** 

**Thank you** for providing this wonderful code.

I tried it, and it works perfectly.

I need to know how to **specify folder paths** in a **config.json** file when there are **two folders** with the same name at **different locations**. Could you please provide guidance on this?(with example).

Thanks & Regards
- Sai

**Comment by cmartinezal** [comment]
Hello @Sai-1411 

Thank you for your comment. 
The code has been updated to include the case of multiple folders with the same name. 
No changes are needed in the config.json file, It should download all folders found now.
